/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import database.UserSession;

/**
 *
 * @author candzon
 */
public class fMain extends javax.swing.JFrame {

    /**
     * Creates new form fMain
     */
    public fMain() {
        initComponents();
        setMenuAccess();
        setName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnMenu = new javax.swing.JMenu();
        mnPaketMakanan = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenuItem();
        mnUser = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Created by Feri");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/warteg-logo.png"))); // NOI18N

        jLabel3.setText("Selamat datang, ");

        lblNama.setText("Nama");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel2)
                .addContainerGap(284, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNama)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblNama))
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 255, 102));

        mnMenu.setText("Menu");
        mnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMenuActionPerformed(evt);
            }
        });

        mnPaketMakanan.setText("Paket Makanan");
        mnPaketMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPaketMakananActionPerformed(evt);
            }
        });
        mnMenu.add(mnPaketMakanan);

        mnTransaksi.setText("Transaksi");
        mnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransaksiActionPerformed(evt);
            }
        });
        mnMenu.add(mnTransaksi);

        mnUser.setText("User");
        mnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUserActionPerformed(evt);
            }
        });
        mnMenu.add(mnUser);

        jMenuBar1.add(mnMenu);

        jMenu2.setText("Lainnya");

        mnLogout.setText("Logout");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        jMenu2.add(mnLogout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnPaketMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPaketMakananActionPerformed
        // TODO add your handling code here:
        // Tutup form saat ini
        this.dispose();

        //Tampilkan kembali form Main
        fPaketMakanan paketMakananFrame = new fPaketMakanan();
        paketMakananFrame.setVisible(true);
        paketMakananFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_mnPaketMakananActionPerformed

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        // TODO add your handling code here:
        // Tutup form saat ini
        this.dispose();

        //Tampilkan kembali form Login
        fLogin loginFrame = new fLogin();
        loginFrame.setVisible(true);
        // Posisi frame di tengah
        loginFrame.setLocationRelativeTo(null);

    }//GEN-LAST:event_mnLogoutActionPerformed

    private void mnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransaksiActionPerformed
        // TODO add your handling code here:
        // Tutup form saat ini
        this.dispose();

        //Tampilkan kembali form Main
        fTransaksi transaksiFrame = new fTransaksi();
        transaksiFrame.setVisible(true);
        transaksiFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_mnTransaksiActionPerformed

    private void mnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUserActionPerformed
        // TODO add your handling code here:
        // Tutup form saat ini
        this.dispose();

        //Tampilkan kembali form Main
        fUser userFrame = new fUser();
        userFrame.setVisible(true);
        userFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_mnUserActionPerformed

    private void mnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMenuActionPerformed
        // TODO add your handling code here:
        int idRole = UserSession.getIdRole();
        // Reset semua menu item menjadi tidak aktif atau tidak terlihat
        mnUser.setVisible(false);
        mnTransaksi.setVisible(false);
        mnPaketMakanan.setVisible(false);

        // Atur visibilitas berdasarkan idRole
        if (idRole == 1) {
            mnUser.setVisible(true);
        } else if (idRole == 2) {
            mnTransaksi.setVisible(true);
        } else if (idRole == 3) {
            mnTransaksi.setVisible(true);
            mnPaketMakanan.setVisible(true);
        }
    }//GEN-LAST:event_mnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fMain().setVisible(true);
            }
        });
    }
    
    private void setMenuAccess() {
        // Ambil idRole dari UserSession
        int idRole = UserSession.getIdRole();

        // Reset semua menu item menjadi tidak aktif atau tidak terlihat
        mnUser.setVisible(false);
        mnTransaksi.setVisible(false);
        mnPaketMakanan.setVisible(false);

        // Atur visibilitas berdasarkan idRole
        if (idRole == 1) {
            mnUser.setVisible(true);
        } else if (idRole == 2) {
            mnTransaksi.setVisible(true);
        } else if (idRole == 3) {
            mnTransaksi.setVisible(true);
            mnPaketMakanan.setVisible(true);
        }
    }
    
    private void setName()
    {
        lblNama.setText(UserSession.getName());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNama;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenu mnMenu;
    private javax.swing.JMenuItem mnPaketMakanan;
    private javax.swing.JMenuItem mnTransaksi;
    private javax.swing.JMenuItem mnUser;
    // End of variables declaration//GEN-END:variables
}
